In [9]:
import numpy as np
import torch

In [2]:
t = np.array([0,1,2,3,4,5,6])
t

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [4]:
print(t.ndim, t.shape)

1 (7,)


In [5]:
print(t[0], t[1], t[2])

0.0 1.0 2.0


In [7]:
print(t[2:5], t[4:-1])

[2. 3. 4.] [4. 5.]


In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [10]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [11]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
t
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [12]:
print(ft.shape)

torch.Size([2, 2, 3])


In [14]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [15]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)


tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
