In [1]:
#Logistic Regression 04-02
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


In [3]:
model = nn.Sequential(nn.Linear(2,1), nn.Sigmoid())

In [4]:
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [9]:
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs =1000
for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 ==0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/1000 Cost: 0.620154 Accuracy 50.00%
Epoch   10/1000 Cost: 0.493700 Accuracy 66.67%
Epoch   20/1000 Cost: 0.426489 Accuracy 66.67%
Epoch   30/1000 Cost: 0.361094 Accuracy 83.33%
Epoch   40/1000 Cost: 0.305882 Accuracy 83.33%
Epoch   50/1000 Cost: 0.256603 Accuracy 83.33%
Epoch   60/1000 Cost: 0.212054 Accuracy 100.00%
Epoch   70/1000 Cost: 0.175886 Accuracy 100.00%
Epoch   80/1000 Cost: 0.154053 Accuracy 100.00%
Epoch   90/1000 Cost: 0.141991 Accuracy 100.00%
Epoch  100/1000 Cost: 0.132478 Accuracy 100.00%
Epoch  110/1000 Cost: 0.124198 Accuracy 100.00%
Epoch  120/1000 Cost: 0.116910 Accuracy 100.00%
Epoch  130/1000 Cost: 0.110446 Accuracy 100.00%
Epoch  140/1000 Cost: 0.104674 Accuracy 100.00%
Epoch  150/1000 Cost: 0.099488 Accuracy 100.00%
Epoch  160/1000 Cost: 0.094803 Accuracy 100.00%
Epoch  170/1000 Cost: 0.090550 Accuracy 100.00%
Epoch  180/1000 Cost: 0.086671 Accuracy 100.00%
Epoch  190/1000 Cost: 0.083119 Accuracy 100.00%
Epoch  200/1000 Cost: 0.079854 Accuracy 100.00

In [10]:
model(x_train)

tensor([[2.7490e-04],
        [3.1539e-02],
        [3.8886e-02],
        [9.5631e-01],
        [9.9824e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [11]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2552, 1.5191]], requires_grad=True), Parameter containing:
tensor([-14.4923], requires_grad=True)]
