In [19]:
import torch
import torch.nn.functional as F

In [20]:
torch.manual_seed(2)

In [21]:
z = torch.FloatTensor([1, 2, 3])

In [22]:
hypothesis = F.softmax(z, dim=0)
print([hypothesis])

[tensor([0.0900, 0.2447, 0.6652])]


In [23]:
hypothesis.sum()

tensor(1.)

In [24]:
z = torch.rand(3,5, requires_grad=True)

In [25]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2089, 0.1654, 0.2136, 0.1816, 0.2306],
        [0.2502, 0.2098, 0.1483, 0.2490, 0.1427],
        [0.1929, 0.1867, 0.1618, 0.2718, 0.1867]], grad_fn=<SoftmaxBackward0>)


In [26]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([3, 4, 2])


In [28]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.]])

In [30]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()

In [31]:
print(cost)

tensor(1.8249, grad_fn=<MeanBackward0>)


In [32]:
torch.log(F.softmax(z, dim=1))

tensor([[-1.5660, -1.7997, -1.5436, -1.7062, -1.4671],
        [-1.3853, -1.5618, -1.9086, -1.3902, -1.9470],
        [-1.6457, -1.6782, -1.8213, -1.3025, -1.6780]], grad_fn=<LogBackward0>)